services:
  web:
    container_name: icrcs-fe-portal
    image: 10.248.0.7:30000/icrcs-fe-portal:v0.9.0
    # If you want Compose to handle the build process automatically when needed:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6060:6060"
    env_file:
      - .env
    environment:
      - PORT=6060
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    
    # -------------------------------------------------------------
    # OPTIONAL: Un-comment the blocks below ONLY for local development.
    # This enables Hot-Reloading so you don't have to rebuild.
    # -------------------------------------------------------------
    # command: npm run dev
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    #   - /app/.next